# Site Settings
title: "Billy's CV"
description: "Billy Tomaszewski - CV"
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Billy <br> <i>Tomaszewski </i>
tagline: Immunology PhD
pic: Headshot.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Immunologist with a focus in unravelling the immune contribution to solid tumor progression by leveraging the advances in systems biology and translating these insights into therapeutics. Currently a Scientist III in the lab of Dr. Baptiste Jaeger at Genentech. Completed PhD training in the labs of Prof. John Sampson and Prof. Michael Gunn at Duke University (Durham, NC). 13 years of cross-disciplinary experience in the field of immunology has given me a unique perspective on the complex nature of the field.'

#sidebar links
email: tomaszewski.billy@gene.com
phone: 
website:  #do not add http://
linkedin: billy-tomaszewski
github: wht10
twitter: 
scholar: HQF4ZLIAAAAJ
orcid: 0000-0001-7870-3935
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113953128-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
