# Site Settings
title: "Billy's CV"
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Billy <br> <i>Tomaszewski </i>
tagline: PhD Candidate
pic: headshot.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Immunologist with a focus in unravelling the immune contribution to neurological disease by leveraging the advances in systems biology. Currently a PhD Candidate in the labs of Prof. John Sampson and Prof. Michael Gunn at Duke University (Durham, NC). 8 years of cross-disciplinary experience in the field of neuroimmunology has given me a unique perspective on teh complex nature of the field.'

#sidebar links
email: william.tomaszewski@duke.edu
phone: 
website:  #do not add http://
linkedin: billy-tomaszewski
github: wht10
twitter: '@BillyTomski'
scholar: mR7Jk7wAAAAJ
orcid: 0000-0001-7870-3935
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113953128-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
