# Site Settings
title: "Elena's CV"
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Elena <br> <i>Torlai Triglia</i>
tagline: Postdoctoral researcher
pic: pic.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Computational and molecular biologist. Currently a postdoc in the lab of Prof. Aviv Regev at the Broad Institute (Cambridge, MA). Previously, I was a PhD student in the Humboldt university of Berlin, working with Prof. Ana Pombo at the Berlin Institute for Medical Systems Biology (@ Max Delbruck Center for Molecular Medicine). Captivated by multidisciplinary, open research. Interested in gene regulation, epigenetics, single-cell and systems biology. Aiming to improve our understanding of cell states.'

#sidebar links
email: etorlait@broadinstitute.org
phone: 
website:  #do not add http://
linkedin: elena-torlai-triglia
github: ElenaTT
twitter: '@ele_tt'
scholar: 9-XWIZIAAAAJ
orcid: 0000-0002-6059-0116
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113953128-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
